"""Add username column to Message

Revision ID: 508cba9e65cb
Revises: 9d5e0fe74280
Create Date: 2025-06-22 10:58:23.364603

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '508cba9e65cb'
down_revision = '9d5e0fe74280'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('username', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'username')
    # ### end Alembic commands ###
